### PR TITLE
Adding conda-tree like dependency printing functionality to mamba

### PR DESCRIPTION
**Pull request by rutujasurve94**
Prints dependency tree for query like:
mamba repoquery python --installed
as
python-v-3.7.6
├─ld_impl_linux-64
├─libffi
├─libgcc-ng
├─libstdcxx-ng
├─ncurses
├─openssl
├─readline
├─sqlite
├─tk
├─xz
├─zlib

Supporting 3 levels of recursive dependency graph, printing package name and version

### CODE REVIEW

**Comment by wolfv** [comment]
Hi @rutujasurve94 good work!

I think it would be best if this functionality goes under a dedicated command, for example `mamba tree xtensor` or similar. I guess this only has to work for multiple levels with the installed packages. Then we can query the installed repo further for the other names and print them recursively as you started. 

For non-installed packages it's enough to just print the dependencies of the first level (because otherwise we would need to find a solution to the dependencies first.

Also as discussed on gitter, if we could print the "EVR" information after the package name, that would be awesome.

**Comment by rutujasurve94** [comment]
Hi, I have updated the code enabling recursion for 3 levels (Prints recursive deps successfully) and also the version along with the name of the solvable. Reg moving it under a different command - will start making changes to mamba.py accordingly

**Comment by rutujasurve94** [comment]
Updated the code, being able to recursively print 3 levels of deps for any package as (for eg. python):
python-v-3.7.6
|- ld_impl_linux-64-v-2.33.1
|- libffi-v-3.2.1
|- |- libgcc-ng-v-9.1.0
|- |- |- _libgcc_mutex-v-0.1
|- |- libstdcxx-ng-v-9.1.0
|- libgcc-ng-v-9.1.0
|- |- _libgcc_mutex-v-0.1
|- libstdcxx-ng-v-9.1.0
|- ncurses-v-6.2
|- |- libgcc-ng-v-9.1.0
|- |- |- _libgcc_mutex-v-0.1
|- |- libstdcxx-ng-v-9.1.0
|- openssl-v-1.1.1g
|- |- ca-certificates-v-2020.4.5.1
|- |- libgcc-ng-v-9.1.0
|- |- |- _libgcc_mutex-v-0.1
|- readline-v-7.0
|- |- libgcc-ng-v-9.1.0
|- |- |- _libgcc_mutex-v-0.1
|- |- ncurses-v-6.2
|- |- |- libgcc-ng-v-9.1.0
|- |- |- libstdcxx-ng-v-9.1.0
|- sqlite-v-3.31.1
|- |- libedit-v-3.1.20181209
|- |- |- libgcc-ng-v-9.1.0
|- |- |- ncurses-v-6.2
|- |- libgcc-ng-v-9.1.0
|- |- |- _libgcc_mutex-v-0.1
|- tk-v-8.6.8
|- |- libgcc-ng-v-9.1.0
|- |- |- _libgcc_mutex-v-0.1
|- |- zlib-v-1.2.11
|- |- |- libgcc-ng-v-9.1.0
|- xz-v-5.2.4
|- |- libgcc-ng-v-9.1.0
|- |- |- _libgcc_mutex-v-0.1
|- zlib-v-1.2.11
|- |- libgcc-ng-v-9.1.0
|- |- |- _libgcc_mutex-v-0.1

**Comment by wolfv** [comment]
that's really cool!

**Comment by rutujasurve94** [comment]
Updated the code to include x74 (t like)ascii character for printing conda tree deps and moving the query under ```--tree``` flag

**Comment by wolfv** [comment]
awesome. let's merge this :)

**Pull request merged**
