### PR TITLE
Test track features

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Should pass once https://github.com/conda-forge/libsolv-feedstock/pull/22 is merged.

**Comment by wolfv** [comment]
merged the conda-forge recipe! looking forward to see these tests pass :)

**Comment by davidbrochart** [comment]
Trigger CI.

**Comment by davidbrochart** [comment]
Oh I should wait a bit.

**Comment by davidbrochart** [comment]
Good to go!

**Pull request merged**
