### PR TITLE
Channel

### PR DESCRIPTION
**Pull request by JohanMabille**
@wolfv It seems that we have to implement some features from MultiChannel for channel prioritization. However I think we can really simplify it (a simple additional multiname member in the Channel class, that remains empty if the Channel is not a multi channel).

### CODE REVIEW

**Comment by wolfv** [comment]
weird, tests aren't running ...

**Comment by JohanMabille** [comment]
yep, let me push an empty commit.

**Comment by JohanMabille** [comment]
This is overgreen!

**Comment by JohanMabille** [comment]
This is ready for a review. There are still some issues when using the C++ implementation of Channel from the C++, but I think this one can be merged  nevertheless.

**Pull request merged**
