### PR TITLE
fix build string reading and saving

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
cc @davidbrochart this should fix the cython issue :)

**Comment by davidbrochart** [comment]
Awesome, let me try it out.

**Comment by davidbrochart** [comment]
Issue solved, thanks!

**Comment by wolfv** [comment]
btw did you try `-v`? it shows you exactly which file was causing trouble

**Comment by davidbrochart** [comment]
No I didn't know, good to know for next time!

**Comment by wolfv** [comment]
cool!

**Pull request merged**
