### PR TITLE
Support channel::package

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
I cannot add tests with local channels, even conda doesn't allow `channel_a::pkg` if `channel_a` is local, it tries to get it from `https://conda.anaconda.org/channel_a`.

**Comment by dhirschfeld** [comment]
Sounds like the default channel alias interfering:
https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#set-ch-alias

Does using a `file://` url work?

**Comment by davidbrochart** [comment]
> Does using a `file://` url work?

no, it doesn't either.

**Comment by dhirschfeld** [comment]
Yeah, I wasn't sure that the `channel::pkg` syntax worked with full urls - seems like it probably *should* though.

**Comment by davidbrochart** [comment]
I filed an issue: https://github.com/conda/conda/issues/9828

**Comment by wolfv** [comment]
I skipped merging this PR because I'd like to not parse the JSON from Python. I'll try to come up with some refactoring to do this through libsolv :)

**Comment by wolfv** [comment]
I have just merged the exact same idea, implemented in C++ #277 :tada;

**Pull request closed without merging**
