### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
@wolfv it looks like for python3.6 on OSX clang want a `libc++` instead of a `libstdc++`: https://github.com/QuantStack/mamba/pull/97/checks?check_run_id=551213487

**Comment by wolfv** [comment]
cool tests! 

hnggh that's annoying! I don't really know what to do here... Maybe @SylvainCorlay has an idea? 

I am unsure what stdlib should be used with conda... and conda-build might do some magic tricks... do we install the compilers with conda here?

**Comment by SylvainCorlay** [comment]
The conda package is libcxx.

**Comment by davidbrochart** [comment]
Same issue on OSX python3.6:
```
g++ -bundle -undefined dynamic_lookup -L/usr/local/miniconda/envs/mamba-tests/lib -arch x86_64 -L/usr/local/miniconda/envs/mamba-tests/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/include/py_interface.o build/temp.macosx-10.7-x86_64-3.6/include/solver.o -lsolv -lsolvext -o build/lib.macosx-10.7-x86_64-3.6/mamba/mamba_api.cpython-36m-darwin.so
  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  ld: library not found for -lstdc++
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'g++' failed with exit status 1
```

**Comment by SylvainCorlay** [comment]
@davidbrochart I don't think it is useful to install libcxx unless you are building with the associated compiler.

**Comment by davidbrochart** [comment]
@wolfv the compilation errors on Windows are a bit cryptic:
```
C:\Miniconda\envs\mamba-tests\Library\include\solv\solvable.h(41): error C2059: syntax error: 'requires'
C:\Miniconda\envs\mamba-tests\Library\include\solv\solvable.h(41): error C2238: unexpected token(s) preceding ';'
```

This is referring to: https://github.com/openSUSE/libsolv/blob/master/src/solvable.h#L41

**Comment by wolfv** [comment]
hmmm on a first guess I woudl think that windows somehow defines `requires` as something else. 
let me check

**Comment by wolfv** [comment]
do you know if it would be possible to use MSVC 2017? MSVC 2019 might still be buggy

**Comment by davidbrochart** [comment]
@wolfv with MSVC 2017 we now get:
```
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Miniconda\envs\mamba-tests\Library\lib\ /LIBPATH:C:\Miniconda\envs\mamba-tests\libs /LIBPATH:C:\Miniconda\envs\mamba-tests\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" solv.lib solvext.lib /EXPORT:PyInit_mamba_api build\temp.win-amd64-3.6\Release\include/py_interface.obj build\temp.win-amd64-3.6\Release\include/solver.obj /OUT:build\lib.win-amd64-3.6\mamba\mamba_api.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\include\mamba_api.cp36-win_amd64.lib
  fatal error C1047: The object or library file 'C:\Miniconda\envs\mamba-tests\Library\lib\solv.lib' was created with an older compiler than other objects; rebuild old objects and libraries
  LINK : fatal error LNK1257: code generation failed
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1257
```

**Comment by wolfv** [comment]
wow, windows sucks so much. Let me check something real quick.

**Comment by wolfv** [comment]
hmm. so maybe using this meta-package from conda-forge would give us the right compiler:

https://anaconda.org/conda-forge/cxx-compiler

**Comment by wolfv** [comment]
at least OS X was fixed :sweat_smile:

**Comment by davidbrochart** [comment]
Yes! But it looks like Windows doesn't use the conda compilers.

**Comment by wolfv** [comment]
we could disable the tests for win for the moment and wait for the migration to vs2017 to be finished. 

Not sure what's going on here. But we have a compile check and a small functional check when we update the feedstock...

**Pull request merged**
