### PR TITLE
Initial implementation of QueryResult

### PR DESCRIPTION
**Pull request by JohanMabille**
This is an early preview of the new QueryResult class so we can review / comment.

### CODE REVIEW

**Comment by wolfv** [comment]
Looks good to me.
I think one question / problem we still have is how to collect the data:

Do we store everything as a tree? (search could be stored with everything having a nullptr as parent?). Or do we construct the tree on the fly from the given values?

**Comment by JohanMabille** [comment]
My idea was to store everything as a list (meaning this is where the ownership is), and have list / tree view on it. The tree view is always built for depends and whoneeds, and on the fly for search.

Also we store a tree, not a graph, so not sure to get what you mean about nullptr as parent.

**Comment by JohanMabille** [comment]
@wolfv I think this is ready to be merged. I've tested mamba repoquery (all commands) on xtensor, it works like a charm.

**Comment by wolfv** [comment]
awesome

**Pull request merged**
