### PR TITLE
Fix for stdout with different encoding than utf-8 

### PR DESCRIPTION
**Pull request by marcelotrevisani**

### CODE REVIEW

**Comment by wolfv** [comment]
python 3.6 still fails unfortunately.

**Comment by marcelotrevisani** [comment]
@wolfv all green now! :tada:  :tada:  :tada:  :tada:

**Comment by wolfv** [comment]
Thanks a lot. I will make a release right now.

**Comment by marcelotrevisani** [comment]
> Thanks a lot. I will make a release right now.

Nice! Thanks for that! :)

**Pull request merged**
